# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [14]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.3310275  0.9453634  0.44921235 ... 0.26633489 0.90176549 0.37276856]
 [0.65780436 0.82183319 0.29078442 ... 0.81695649 0.56200544 0.59053294]
 [0.27682383 0.78035059 0.78039661 ... 0.87206678 0.12731045 0.72555829]
 ...
 [0.38244007 0.49629272 0.01597609 ... 0.13081176 0.15821316 0.87593377]
 [0.35134485 0.09561921 0.55672968 ... 0.90749419 0.43492026 0.15018803]
 [0.87129273 0.47776269 0.08618136 ... 0.73992127 0.73459053 0.73222191]]
[[0.66476668 0.61008321 0.12520147 ... 0.36908139 0.25381621 0.6359497 ]
 [0.99772071 0.72415867 0.14147347 ... 0.65302009 0.38643719 0.39656421]
 [0.89575733 0.89149491 0.17245096 ... 0.53244957 0.52989639 0.12226096]
 ...
 [0.90389327 0.99439033 0.30017357 ... 0.80802209 0.73268279 0.53694245]
 [0.33925763 0.13808708 0.13135379 ... 0.90824565 0.67924593 0.26049682]
 [0.47038254 0.35644821 0.66185855 ... 0.21538798 0.24984968 0.57536781]]


Без использования numpy

In [15]:
def mult(a, b):
    result = [[0 for row in range(len(b))] for col in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(a[0])):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [16]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 734 ms
Wall time: 747 ms


In [17]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3528733688872308e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.58845822 0.36935804 0.03491262] [0.66598661 0.75131573 0.26298963]


In [ ]:
def scalar_product(a,b):
    result = sum([i * j for i, j in zip(a, b)])
    return result

In [ ]:
def np_scalar_product(a,b):
    result = np.dot(a, b)
    return result

In [19]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


19113.91720290572

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy оказываются эффективнее благодаря тому, что они реализованы на языке программирования C, что обеспечивает им высокую скорость выполнения. Кроме того, NumPy использует векторизацию операций, что позволяет выполнять операции над массивами данных более эффективно, чем стандартные циклы. 
Скорость вычислений в NumPy обычно является очень высокой, особенно при работе с большими массивами данных.

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [23]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    result = 0
    diagonal = [a[i][i] for i in range(len(a))]
    for elem in range(len(diagonal)):
        if diagonal[elem] % 2 == 0:
            result += diagonal[elem]
    return result

In [24]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 8, 5, 1, 6],
       [9, 4, 9, 2, 8],
       [6, 4, 8, 8, 3],
       [4, 1, 9, 5, 2],
       [2, 3, 1, 3, 1]])

In [25]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [29]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    cumsum = np.cumsum(A)
    k = np.arange(1, len(A) + 1)
    s = cumsum / k
    return s

In [30]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.23233726 0.81170941 0.2691404  0.26860921 0.64137859 0.90012084
 0.9812267  0.04146995 0.01354703 0.58398571 0.97108399 0.47399285
 0.52116158 0.71200649 0.59027932 0.39728144 0.17013196 0.68238242
 0.13955317 0.00352982 0.97335451 0.34144061 0.88007139 0.83394186
 0.77416166 0.62427366 0.99779624 0.21265426 0.32444504 0.52539502
 0.16957402 0.94289652 0.87701227 0.92985767 0.93901462 0.63047209
 0.786211   0.91422117 0.21810868 0.89508136 0.90343573 0.38581413
 0.1448979  0.88396209 0.38242484 0.49241828 0.77114267 0.28885653
 0.97031384 0.77746168 0.29786155 0.79526319 0.27939378 0.78912442
 0.32320801 0.51711825 0.02466302 0.94722126 0.05117054 0.17297628
 0.06766478 0.16547697 0.76700344 0.58544521 0.76832804 0.80889744
 0.1686232  0.68754181 0.8327591  0.46436937 0.27428503 0.18811033
 0.17137039 0.97218742 0.31915337 0.60604995 0.76829994 0.28534521
 0.88136787 0.03384112 0.65462934 0.14857167 0.76084537 0.68673997
 0.85676798 0.5163803  0.14819269 0.68745253 0.66135569 0.4870

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [31]:
# функция, решающая задачу с помощью NumPy
def np_encode(array):
    elem_array = []
    count_elem = []
    k = 1
    for i in range(1, len(array)):
        if array[i] == array[i-1]:
            k += 1
        else:
            elem_array.append(array[i-1])
            count_elem.append(k)
            k = 1
    elem_array.append(array[-1])
    count_elem.append(k)
    return elem_array, count_elem

In [37]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
print(np_encode(X))
%time x, num = np_encode(X)

([1, 2, 3, 1, 5, 2, 3], [1, 2, 2, 2, 2, 1, 2])
CPU times: total: 0 ns
Wall time: 0 ns


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [41]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    new_X = X.copy()
    for i in range(len(new_X)):
        if i % 2 != 0:
            new_X = np.where(new_X == new_X[i], a, new_X)
        else:
            new_X = np.where(new_X == new_X[i], new_X[i]**3, new_X)
    return reversed(new_X)

In [43]:
X = np.array([i for i in range(1, 10, 2)])
print("Одномерный массив X:", X)
new_X = [i for i in np_transformation(X)]
print("Преобразованный массив X:", new_X)
result = np.append(X, new_X)
print("Результат:", [elem for elem in result])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

Одномерный массив X: [1 3 5 7 9]
Преобразованный массив X: [729, 1, 125, 1, 1]
Результат: [1, 3, 5, 7, 9, 729, 1, 125, 1, 1]
CPU times: total: 0 ns
Wall time: 0 ns
